### ISSUE TITLE
Experiment Issue

### ISSUE THREAD

**Issue by EricHusa** [sarpongdk/fopd-flask-api#2]
127.0.0.1 - - [02/May/2020 21:08:22] "POST /api/experiment/teacher/03dc863d-7811-411f-b70b-4a0837ab5c0f HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/fopd/experiments/routes.py", line 191, in create_experiment
    device = device
  File "<string>", line 4, in __init__
    
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/base.py", line 842, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 272, in __set__
    instance_state(instance), instance_dict(instance), value, None
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 1018, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 1041, in fire_replace_event
    state, value, previous, initiator or self._replace_token
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 1450, in emit_backref_from_scalar_set_event
    instance_state(child),
AttributeError: 'BaseQuery' object has no attribute '_sa_instance_state'

**Comment by sarpongdk** [comment]
fixed
