### ISSUE TITLE
When updating an assignment - PUT assignment/${assignmentId}/teacher/${id}

### ISSUE THREAD

**Issue by EricHusa** [sarpongdk/fopd-flask-api#3]
Traceback (most recent call last):
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  **File "/Users/eric/PycharmProjects/testback/fopd-flask-api/fopd/assignments/routes.py", line 259, in update_assignment
    assignment.students.append(student)**
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/orm/collections.py", line 1113, in append
    item = __set(self, item, _sa_initiator)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/orm/collections.py", line 1078, in __set
    item = executor.fire_append_event(item, _sa_initiator)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/orm/collections.py", line 715, in fire_append_event
    self.owner_state, self.owner_state.dict, item, initiator
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 1177, in fire_append_event
    value = fn(state, value, initiator or self._append_token)
  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/nv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 45, in append
    item_state = attributes.instance_state(item)
**AttributeError: 'BaseQuery' object has no attribute '_sa_instance_state'**

**Comment by EricHusa** [comment]
^ Fixed it but will let you decide if that is the correct fix
